---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
  labels:
    k8s.mariadb.com/watch: ""
data:
  my.cnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M
---
{{- $rootPasswordSecret := .Values.mariadbRootPasswordSecret.name | default "mariadb-root-password" -}}
{{- $appPasswordSecret := .Values.mariadbAppPasswordSecret.name | default "mariadb-app-password" -}}
{{- $maxscalePasswordSecret := .Values.maxscalePasswordSecret.name | default "maxscale" -}}
{{- if not (lookup "v1" "Secret" .Release.Namespace $rootPasswordSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $rootPasswordSecret }}
  labels:
    k8s.mariadb.com/watch: ""
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data: {}
{{- end -}}
---
{{- if not (lookup "v1" "Secret" .Release.Namespace $appPasswordSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appPasswordSecret }}
  labels:
    k8s.mariadb.com/watch: ""
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data: {}
{{- end -}}
---
{{- if not (lookup "v1" "Secret" .Release.Namespace $maxscalePasswordSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $maxscalePasswordSecret }}
  labels:
    k8s.mariadb.com/watch: ""
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data: {}
{{- end -}}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: {{ $rootPasswordSecret }}
    key: password
  username: opsdata
  passwordSecretKeyRef:
    name: {{ $appPasswordSecret }}
    key: password
  database: opsdata
  storage:
    size: 8Gi
    storageClassName: harvester
    resizeInUseVolumes: true
    waitForVolumeResize: true
    volumeClaimTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: harvester
  replicas: 3
  maxScale:
    enabled: true
    kubernetesService:
      type: LoadBalancer
    connection:
      secretName: mxs-galera-conn
      port: 3306
  galera:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: true
    sst: mariabackup
    availableWhenDonor: false
    galeraLibPath: /usr/lib/galera/libgalera_smm.so
    replicaThreads: 1
    providerOptions:
      gcs.fc_limit: '64'
    agent:
      image: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:v0.0.29
      port: 5555
      kubernetesAuth:
        enabled: true
      gracefulShutdownTimeout: 1s
    recovery:
      enabled: true
      minClusterSize: 50%
      clusterMonitorInterval: 10s
      clusterHealthyTimeout: 30s
      clusterBootstrapTimeout: 10m
      podRecoveryTimeout: 3m
      podSyncTimeout: 3m
    initContainer:
      image: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:v0.0.29
    initJob:
      metadata:
        labels:
          sidecar.istio.io/inject: "false"
      args:
        - "--verbose"
      affinity:
        antiAffinityEnabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 1Gi
    config:
      reuseStorageVolume: false
      volumeClaimTemplate:
        resources:
          requests:
            storage: 300Mi
        accessModes:
          - ReadWriteOnce
  service:
    type: LoadBalancer
  connection:
    secretName: mariadb-galera-conn
    secretTemplate:
      key: dsn
  primaryService:
    type: ClusterIP
  primaryConnection:
    secretName: mariadb-galera-conn-primary
    secretTemplate:
      key: dsn
  secondaryService:
    type: ClusterIP
  secondaryConnection:
    secretName: mariadb-galera-conn-secondary
    secretTemplate:
      key: dsn
  affinity:
    antiAffinityEnabled: true
  podDisruptionBudget:
    maxUnavailable: 33%
  updateStrategy:
    type: ReplicasFirstPrimaryLast
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
  metrics:
    enabled: true
