{{- $jwtSecretName := .Values.secretGenerator.jwtSecret.name | default "jwt-secret" -}}
{{- $encryptionKeyName := .Values.secretGenerator.encryptionKey.name | default "encryption-key" -}}

{{- if not (lookup "v1" "Secret" .Release.Namespace $jwtSecretName) }}
---
apiVersion: "k8s.mittwald.de/v1alpha1"
kind: SecretGenerator
metadata:
  name: opsdata-jwt-secret
spec:
  secrets:
    - name: {{ $jwtSecretName }}
      length: {{ .Values.secretGenerator.jwtSecret.length }}
      type: Opaque
{{- end }}

{{- if not (lookup "v1" "Secret" .Release.Namespace $encryptionKeyName) }}
---
apiVersion: "k8s.mittwald.de/v1alpha1"
kind: SecretGenerator
metadata:
  name: opsdata-encryption-key
spec:
  secrets:
    - name: {{ $encryptionKeyName }}
      length: {{ .Values.secretGenerator.encryptionKey.length }}
      type: Opaque
{{- end }}
