apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: "opsdata"
    component: "frontend"
    release: "{{ .Release.Name }}"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"  # Ensure port is quoted to be interpreted as string
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: metrics
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: "opsdata"
    component: "frontend"
    release: "{{ .Release.Name }}"
